### ISSUE TITLE
number output clashes with directory name

### ISSUE THREAD

**Issue by kasperlewau** [mroth/scmpuff#48]
Given the following directory structure: 

```sh
▸ tree
.
├── 1
│   ├── a.txt
│   └── b.txt
└── 2.txt

1 directory, 3 files
``` 

And a git history as such: 

```sh
commit 4a89f1d42dea3f0378351566c40dffe2e961abb3 (HEAD -> master)
Author: Kasper Lewau <lewauu@gmail.com>
Date:   Mon Aug 19 08:11:34 2019 +0200

    init

diff --git a/1/a.txt b/1/a.txt
new file mode 100644
index 0000000..e69de29
diff --git a/1/b.txt b/1/b.txt
new file mode 100644
index 0000000..e69de29
diff --git a/2.txt b/2.txt
new file mode 100644
index 0000000..e69de29
```

If I modify `1/{a,b}.txt` and issue `gd 1` to diff the first change, the diff for everything under `1/` prints. 

```sh
▸ gs
# On branch: master  |  [*] => $e*
#
➤ Changes not staged for commit
#
#       modified:  [1] 1/a.txt
#       modified:  [2] 1/b.txt
#
``` 

```sh
▸ gd 1
diff --git a/1/a.txt b/1/a.txt
index e69de29..45b983b 100644
--- a/1/a.txt
+++ b/1/a.txt
@@ -0,0 +1 @@
+hi
diff --git a/1/b.txt b/1/b.txt
index e69de29..30e8a65 100644
--- a/1/b.txt
+++ b/1/b.txt
@@ -0,0 +1 @@
+there
``` 

First time I stumble onto this, and I've been using `scmpuff` for quite some time now. I cannot rule out a busted shell/environment on my end, I'll try and reproduce on a fresh system and update the issue.

**Comment by mroth** [comment]
This behavior is intentional, and I'm not sure there is a reasonable workaround.  Scmpuff will check if a number represents a physical file before expanding it, to prevent unexpected behavior when someone is attempting to operate on an actual file.

In this edge case situation, you would probably want to specify the exact substitution via the environment variable, e.g. `$e1` instead of `1`.
