### ISSUE TITLE
Wrappers for common shell commands

### ISSUE THREAD

**Issue by jawshooah** [mroth/scmpuff#5]
One thing I miss from SCM Breeze is the ability to wrap common shell utilities like `cp`, `mv`, `ls`, `vim`, etc. For example:

```bash
$ gs
# On branch: master  |  +1  |  [*] => $e*
#
➤ Changes not staged for commit
#
#       modified:  [1] main.go
#
➤ Untracked files
#
#      untracked:  [2] HELLO.txt
#      untracked:  [3] features/shell_aliases.feature
#      untracked:  [4] mkramdisk.sh
#
$ mv 2 HELLO_AGAIN.txt
$ vim 4
```

How do you feel about adding this feature? Like you, I'm not a fan of the various bloat that SCM Breeze introduces, but I've come to rely on this particular feature, and have built up some muscle memory around it. `vim 4` is much easier to type than `vim $e4`.

**Comment by mroth** [comment]
Thanks for the feedback!

So, generally my philosophy has been to avoid these because I feel it gets really dangerous to wrap common basic commands like those, and having 💯 integration test coverage around all the possible interactions (which I strive for with the git wrapper) is difficult if not impossible.

@jawshooah, do you find you ever do these commands with file ranges?  (e.g. `2-7`)  I personally found I only used them with singleton files, and thus I use the shell environment variables (e.g. `$e1`, `$e2`) that get set when I want to access a file numerically for another command.  Let me know if that addresses the use case.

The other possibility would be to manually create shell wrappers for these commands, and just load them as part of your profile instead of it being bundled with the default `scmpuff init` process.

You can see the git wrapper here:
https://github.com/mroth/scmpuff/blob/master/commands/inits/data/git_wrapper.sh

It would be fairly simple to create similar wrappers for whatever commands you wanted, the general pattern would look something like:

```shell
function cmdname() {
   eval "$(scmpuff expand -- cmdname "$@")";
}
```

We could then create a wiki page or something in the documentation with all these examples for people who wanted to wrap them.  And once they were a little tested, maybe put a shell script in this repository so people could simply source.  But beforehand let me know if the environment variable hack is sufficient, as it's certainly the safest!

**Comment by mroth** [comment]
I'm going to go ahead and close this one now. I appreciate the feedback, but I'm purposefully limiting the feature-set to core functionality only. I hope the workarounds posted here are sufficient!
