### ISSUE TITLE
Easily extensible git aliases

### ISSUE THREAD

**Issue by jeffbyrnes** [mroth/scmpuff#6]
This is almost certainly out-of-scope of this project (similar to #5), but I wanted to bring it up all the same, and get your thoughts.

SCM Breeze offers this awesome, huge collection of git aliases that run through the git wrapper there (courtesy of the `.git.scmbrc` file), e.g., `ga`, `gco`, `gcob`, `gc`, etc.

Any chance of providing this kind of easily extensible aliasing to scmpuff?

**Comment by mroth** [comment]
The nice thing is that because of the way scmpuff wraps git, you can add aliases in the normal way and they should "just work":

For example, I have a few here:
https://github.com/mroth/scmpuff/blob/master/commands/inits/data/aliases.sh

Thus custom ones should be addable to a user's profile in the normal way, and would work with or without scmpuff installed.

I'm not opposed to adding a few more to the default list, but I wanted to keep that list intentionally as short as possible to avoid conflicting with anything a user might have set in the profile (originally I was planning on not including any at all).

Open to thoughts/discussion!

**Comment by montchr** [comment]
How would I go about overriding the `gl` alias, for example? I've added my desired alias to my `.zshrc` file like any other alias but it seems it's still overridden by the alias set in scmpuff.

**Comment by mroth** [comment]
@montchr if you want to override one specifically, just make sure your alias is set afterwards in ordering from initializing scmpuff.  Alternately, you can tell scmpuff not to set any of it's aliases at all by adjusting it's init command in your shell config to something such as `scmpuff init -s --aliases=false`.

**Comment by jeffbyrnes** [comment]
This has been hanging open for a long time, and a great solution was proposed above. Closing out!
